### ISSUE TITLE
Very small formatting typo

### ISSUE THREAD

**Issue by csbenz** [shanraisshan/EmojiCodeSheet#1]
[Here](https://github.com/shanraisshan/EmojiCodeSheet/blob/master/android/string/Nature.java#L170), there is a double space before the comment (after the semi-colon).

Nothing scandalous but caught it while trying to match-replace the data.

By the way, this project is awesome and very handy. I'm currently transforming the data to create a Java enum, here are the regexp values I'm using in case somebody else is interested:

- match `.*(?:String +)([_A-Z\d]+) *= *(?:")(.*)(?:");(?: *(?:\/\/)(.*))?`
- replace `$1("$2"), // $3`

which will yield results of the following format (example with FULL_MOON):
`FULL_MOON("🌕"), // https://www.emojibase.com/emoji/1f315/fullmoonsymbol`

EDIT: modified the 'match' string to take into account the typo and eventual other erratic spacings.

**Comment by shanraisshan** [comment]
fixed.

BTW this project already contains java enums [here](https://github.com/shanraisshan/EmojiCodeSheet/tree/master/java/string) 😉

**Comment by csbenz** [comment]
Are you serious it took me hours to get the result I wanted when it was in an adjacent folder. Anyway, I learned a few tricks I suppose :) Thanks!

**Comment by shanraisshan** [comment]
You should have check the java folder first 😃 
One advice, if you developing for Android check [this](https://github.com/shanraisshan/EmojiCodeSheet/wiki/Android-usage), Android official docs don't recommend enums.

**Comment by csbenz** [comment]
Thanks for the info, I didn't know that. The problem is that I need to be
able to get a  list of all the emojis easily.
Would you still recommend using the final static fields and manually calling each of them?
